// GymSpace Instagram Post Builder - Posts Data (Updated with Slides)
// Based on docs/marketing/instagram-content-strategy.md

import type { PostsData } from './types/post.types';

const postsData: PostsData = {
  1: {
    id: 1,
    title: '¿Todavía manejas tu gimnasio con Excel?',
    day: 'Día 1',
    type: 'Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: '60% de gimnasios pierde 12-18% por errores manuales',
    subtitle:
      'El 60% de los gimnasios en LATAM pierde entre 12-18% de su facturación por errores manuales.',
    description:
      '🎯 60% de gimnasios pierde 12-18% por errores manuales\n\nEl 60% de los gimnasios en LATAM pierde entre 12-18% de su facturación por errores manuales.\n\n✨ Lo que obtienes:\n• Gestión de Miembros: Perfiles completos, contratos digitales y seguimiento\n• WhatsApp Integrado: Mensajes automatizados y campañas masivas\n• Reportes en Tiempo Real: Dashboards y métricas de ingresos\n\n📊 60% de gimnasios usan Excel y pierden dinero\n\nEmpieza gratis →\n\n30 días sin costo · Sin tarjeta',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'GymManagement',
      'Excel',
      'ProblemaSolucion',
      'Eficiencia',
      'TransformacionDigital',
      'Carousel',
      'Swipe',
      'GestionGimnasio',
    ],
    totalSlides: 3,
    slides: [
      {
        title: '¿Todavía manejas tu gimnasio con Excel?',
        subtitle: 'El problema que te está costando dinero',
        layout: 'problem-slide',
        warning: '🚨 Alerta de rentabilidad',
        stat: { value: '60%', label: 'de gimnasios en LATAM usan Excel' },
        message: 'Y pierden entre 12-18% de facturación por errores manuales',
      },
      {
        title: 'El costo real de usar Excel',
        subtitle: 'Esto es lo que pierdes cada mes',
        layout: 'stats-grid',
        stats: [
          { value: '60%', label: 'usan Excel y pierden dinero', icon: 'users' },
          { value: '12-18%', label: 'facturación perdida', icon: 'trending-down' },
          { value: '35%', label: 'abandono sin seguimiento', icon: 'user-x' },
        ],
      },
      {
        title: 'Deja de perder dinero',
        subtitle: 'La solución que tu gimnasio necesita',
        layout: 'solution-slide',
        features: [
          {
            icon: 'users',
            title: 'Gestión de Miembros',
            desc: 'Perfiles completos, contratos digitales y seguimiento',
          },
          {
            icon: 'message-circle',
            title: 'WhatsApp Integrado',
            desc: 'Mensajes automatizados y campañas masivas',
          },
          {
            icon: 'bar-chart-3',
            title: 'Reportes en Tiempo Real',
            desc: 'Dashboards y métricas de ingresos',
          },
        ],
      },
    ],
    stats: [
      { value: '60%', label: 'de gimnasios usan Excel y pierden dinero' },
      { value: '12-18%', label: 'de facturación perdida por errores manuales' },
      { value: '35%', label: 'tasa de abandono por falta de seguimiento' },
    ],
    features: [
      {
        icon: 'users',
        title: 'Gestión de Miembros',
        desc: 'Perfiles completos, contratos digitales y seguimiento',
      },
      {
        icon: 'message-circle',
        title: 'WhatsApp Integrado',
        desc: 'Mensajes automatizados y campañas masivas',
      },
      {
        icon: 'bar-chart-3',
        title: 'Reportes en Tiempo Real',
        desc: 'Dashboards y métricas de ingresos',
      },
    ],
    cta: 'Empieza gratis →',
    ctaNote: '30 días sin costo · Sin tarjeta',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'message-circle', text: '70% tasa de apertura' },
  },
  2: {
    id: 2,
    title: 'Los 5 números que dictan el éxito de tu gimnasio',
    day: 'Día 3',
    type: 'Carousel',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: 'Si no sabes estos números, estás volando a ciegas',
    subtitle:
      'Conocer estos datos te permite tomar decisiones inteligentes y hacer crecer tu negocio.',
    totalSlides: 6,
    slides: [
      {
        title: 'Los 5 números que dictan el éxito',
        subtitle: 'Conócelos antes de que sea tarde',
        content: 'cover',
        stat: '60%',
        statLabel: 'de gimnasios no miden estos datos',
        layout: 'cover',
      },
      {
        title: 'Número #1',
        subtitle: 'La fuga silenciosa',
        content: 'metric-detail',
        metricName: 'Cuántos socios se van cada mes',
        metricValue: 'Churn Rate',
        description:
          'Si 100 socios entran y 5 se van, tu Churn Rate es 5%. La meta: menos del 5% mensual.',
        whyItMatters: 'Un churn alto significa que estás perdiendo dinero constantemente.',
        icon: 'trending-down',
        stat: '< 5%',
        statLabel: 'es la meta mensual',
        layout: 'metric-detail',
      },
      {
        title: 'Número #2',
        subtitle: 'El valor real de cada socio',
        content: 'metric-detail',
        metricName: 'Cuánto dinero deja un socio en total',
        metricValue: 'LTV',
        description: 'Si un socio paga S/ 50/mes y se queda 2 años, su LTV es S/ 1,200.',
        whyItMatters: 'Sabes exactamente cuánto puedes invertir para conseguir un nuevo cliente.',
        icon: 'coins',
        stat: 'S/ 1,200',
        statLabel: 'ejemplo de LTV promedio',
        layout: 'metric-detail',
      },
      {
        title: 'Número #3',
        subtitle: 'El costo de crecer',
        content: 'metric-detail',
        metricName: 'Cuánto te cuesta conseguir un nuevo socio',
        metricValue: 'CAC',
        description: 'Suma todo lo que gastas en marketing y ventas, dividido entre nuevos socios.',
        whyItMatters: 'Si tu CAC es mayor que tu LTV, estás perdiendo dinero con cada nuevo socio.',
        icon: 'target',
        stat: '3:1',
        statLabel: 'ratio ideal LTV:CAC',
        layout: 'metric-detail',
      },
      {
        title: 'Número #4',
        subtitle: 'Aprovecha tu capacidad',
        content: 'metric-detail',
        metricName: 'Qué tan lleno está tu gimnasio',
        metricValue: 'Utilización',
        description: 'Horas pico vs horas valle. Un gimnasio vacío es dinero desperdiciado.',
        whyItMatters: 'Conocer tus horas pico te permite optimizar staff y maximizar ingresos.',
        icon: 'activity',
        stat: '70%',
        statLabel: 'utilización ideal en horas pico',
        layout: 'metric-detail',
      },
      {
        title: 'Número #5',
        subtitle: 'La satisfacción real',
        content: 'metric-detail',
        metricName: 'Tus socios te recomendarían',
        metricValue: 'NPS',
        description:
          "Pregunta: 'Del 0 al 10, qué tan probable es que recomiendes nuestro gimnasio?'",
        whyItMatters: 'Un NPS alto significa crecimiento orgánico por recomendaciones.',
        icon: 'heart',
        stat: '50+',
        statLabel: 'NPS excelente',
        layout: 'metric-detail',
      },
      {
        title: '¿Ya conoces tus números?',
        subtitle: 'Medir es el primer paso para mejorar',
        content: 'final-cta',
        stat: '40%',
        statLabel: 'más rentabilidad con datos claros',
        features: [
          { icon: 'bar-chart-3', title: 'Dashboard', desc: 'Tus métricas en tiempo real' },
          { icon: 'zap', title: 'Alertas', desc: 'Te avisamos cuando algo cambia' },
          { icon: 'trending-up', title: 'Crecimiento', desc: 'Decisiones basadas en datos' },
        ],
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '5 números', label: 'que dictan tu éxito' },
      { value: '< 5%', label: 'meta de abandono mensual' },
      { value: '3:1', label: 'ratio ideal LTV:CAC' },
    ],
    features: [
      { icon: 'bar-chart-3', title: 'Dashboard Visual', desc: 'Tus métricas claras y simples' },
      { icon: 'zap', title: 'Alertas Automáticas', desc: 'Te avisamos cuando algo cambia' },
      { icon: 'trending-up', title: 'Toma Decisiones', desc: 'Basadas en datos, no en intuición' },
    ],
    cta: 'Quiero ver mi dashboard →',
    ctaNote: 'Prueba gratis 30 días',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'bar-chart-3', text: '5 métricas clave' },
    description:
      '🎯 Si no sabes estos números, estás volando a ciegas\n\nConocer estos datos te permite tomar decisiones inteligentes y hacer crecer tu negocio.\n\n✨ Lo que obtienes:\n• Dashboard Visual: Tus métricas claras y simples\n• Alertas Automáticas: Te avisamos cuando algo cambia\n• Toma Decisiones: Basadas en datos, no en intuición\n\n📊 5 números que dictan tu éxito\n\nQuiero ver mi dashboard →\n\nPrueba gratis 30 días',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Educacion',
      'Metricas',
      'Dashboard',
      'ChurnRate',
      'LTV',
      'CAC',
      'GestionDatos',
    ],
  },
  3: {
    id: 3,
    title: 'Tus socios no leen tus emails',
    day: 'Día 5',
    type: 'Reel + Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: '80% de tus mensajes importantes se pierden en el spam',
    subtitle: 'GymSpace te da WhatsApp Business integrado: automatización + mensajería masiva',
    totalSlides: 4,
    slides: [
      {
        title: 'Tus socios no leen tus emails',
        subtitle:
          'El 80% de emails de gimnasios nunca se abren. Hay una mejor forma de comunicarte.',
        content: 'hook-cards',
        stats: [
          { value: '20%', label: 'apertura promedio en email' },
          { value: '70%', label: 'apertura en WhatsApp' },
          { value: '40x', label: 'más veces revisamos WhatsApp' },
        ],
        features: [
          {
            icon: 'message-circle',
            title: 'Mensajes Automatizados',
            desc: 'Bienvenidas, recordatorios, cumpleaños',
          },
          { icon: 'zap', title: 'Mensajería Masiva', desc: 'Campañas segmentadas por etiquetas' },
          {
            icon: 'smartphone',
            title: 'Donde Están Tus Clientes',
            desc: 'WhatsApp: la app #1 en LATAM',
          },
        ],
        layout: 'hook-cards',
      },
      {
        title: 'Email vs GymSpace WhatsApp',
        subtitle: 'La diferencia es abismal',
        content: 'comparison',
        before: {
          title: 'Email tradicional',
          items: ['20% apertura', 'Termina en spam', 'Leído horas después'],
        },
        after: {
          title: 'GymSpace WhatsApp',
          items: ['70% apertura', 'Notificación push', 'Leído en minutos', '100% automatizado'],
        },
        layout: 'two-col-comparison',
      },
      {
        title: '¿Qué automatiza GymSpace?',
        subtitle: 'Configura una vez, funciona siempre',
        content: 'slide-list',
        items: [
          { number: '1', title: 'Bienvenida', desc: 'Al momento de registrar' },
          { number: '2', title: 'Recordatorios', desc: 'Antes de vencer membresía' },
          { number: '3', title: 'Recuperación', desc: 'Si falta 7 días' },
          { number: '4', title: 'Cumpleaños', desc: 'Mensaje personalizado' },
        ],
        layout: 'numbered-list',
      },
      {
        title: 'Mensajería masiva segmentada',
        subtitle: 'Envía campañas a grupos específicos',
        content: 'slide-list',
        items: [
          { number: '1', title: 'Etiquetas inteligentes', desc: 'Por vencer, nuevos, inactivos' },
          {
            number: '2',
            title: 'Campañas promocionales',
            desc: 'Nuevas clases, ofertas especiales',
          },
          { number: '3', title: 'Anuncios importantes', desc: 'A todos o segmentos específicos' },
        ],
        layout: 'numbered-list',
      },
    ],
    stats: [
      { value: '70%', label: 'tasa de apertura en WhatsApp' },
      { value: '20%', label: 'tasa de apertura en Email' },
      { value: '40x', label: 'más veces revisamos WhatsApp' },
    ],
    features: [
      {
        icon: 'message-circle',
        title: 'Mensajes Automatizados',
        desc: 'Bienvenidas, recordatorios, cumpleaños',
      },
      { icon: 'zap', title: 'Mensajería Masiva', desc: 'Campañas segmentadas por etiquetas' },
      {
        icon: 'smartphone',
        title: 'Donde Están Tus Clientes',
        desc: 'El latino revisa WhatsApp 40+ veces al día',
      },
    ],
    cta: 'Prueba 30 días gratis →',
    ctaNote: 'Sin tarjeta, sin compromiso',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'message-circle', text: '70% apertura' },
    description:
      '🎯 80% de tus mensajes importantes se pierden en el spam\n\nGymSpace te da WhatsApp Business integrado: automatización + mensajería masiva\n\n✨ Lo que obtienes:\n• Mensajes Automatizados: Bienvenidas, recordatorios, cumpleaños\n• Mensajería Masiva: Campañas segmentadas por etiquetas\n• Donde Están Tus Clientes: WhatsApp: la app #1 en LATAM\n\n📊 70% tasa de apertura en WhatsApp\n\nPrueba 30 días gratis →\n\nSin tarjeta, sin compromiso',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'WhatsApp',
      'Mensajeria',
      'Comunicacion',
      'MarketingDigital',
      'Retencion',
    ],
  },
  4: {
    id: 4,
    title: 'Por qué tus socios abandonan el gimnasio',
    day: 'Día 7',
    type: 'Carousel',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: 'El 35% de tus socios se irá este año. ¿Sabes por qué?',
    subtitle: 'Entender las razones del abandono es el primer paso para retener a tus clientes.',
    totalSlides: 6,
    slides: [
      {
        title: 'El verdadero costo del abandono',
        subtitle: 'Perder un socio cuesta más que ganar uno nuevo',
        content: 'cover',
        stat: '5x',
        statLabel: 'más caro retener que adquirir',
        layout: 'cover',
      },
      {
        title: 'Razón #1',
        subtitle: 'La falta de conexión',
        content: 'error-detail',
        error: 'No sentirse valorado',
        description:
          'Los socios que no reciben atención personalizada sienten que son solo un número.',
        solution: 'Mensajes personalizados en WhatsApp. Felicita cumpleaños y milestones.',
        icon: 'heart',
        stat: '68%',
        statLabel: 'más retención con comunicación personalizada',
        layout: 'error-detail',
      },
      {
        title: 'Razón #2',
        subtitle: 'La frustración silenciosa',
        content: 'error-detail',
        error: 'Problemas sin resolver',
        description:
          'Cuando un socio tiene una queja y no encuentra respuesta, no vuelve a intentarlo. Simplemente se va.',
        solution: 'Canal directo de comunicación. Responde en minutos, no en días.',
        icon: 'message-circle',
        stat: '70%',
        statLabel: 'de apertura en WhatsApp vs 20% email',
        layout: 'error-detail',
      },
      {
        title: 'Razón #3',
        subtitle: 'La rutina aburrida',
        content: 'error-detail',
        error: 'Falta de variedad',
        description:
          'Hacer lo mismo cada día genera monotonía. Sin nuevos desafíos, los socios pierden motivación.',
        solution: 'Actividades y clases variadas. Retos semanales y programas especiales.',
        icon: 'zap',
        stat: '40%',
        statLabel: 'más asistencia con variedad de actividades',
        layout: 'error-detail',
      },
      {
        title: 'Razón #4',
        subtitle: 'El abandono invisible',
        content: 'error-detail',
        error: 'Detectar la deserción tarde',
        description:
          'Cuando un socio lleva 30 días sin asistir, la probabilidad de que regrese es mínima.',
        solution: 'Alertas automáticas a los 7 días. Interviene antes de que sea tarde.',
        icon: 'bell',
        stat: '25%',
        statLabel: 'reducción en abandono con detección temprana',
        layout: 'error-detail',
      },
      {
        title: 'Razón #5',
        subtitle: 'La falta de compromiso',
        content: 'error-detail',
        error: 'Sin seguimiento de progreso',
        description:
          'Los socios que no ven resultados ni registran su progreso pierden el interés rápidamente.',
        solution: 'Check-ins digitales y seguimiento de asistencia. Muestra su progreso.',
        icon: 'trending-up',
        stat: '3x',
        statLabel: 'más retención con socios comprometidos',
        layout: 'error-detail',
      },
    ],
    stats: [
      { value: '35%', label: 'abandono promedio anual' },
      { value: '5x', label: 'más caro adquirir que retener' },
      { value: '25%', label: 'reducción posible con sistema' },
    ],
    features: [
      { icon: 'heart', title: 'Conexión Emocional', desc: 'Comunicación personalizada' },
      { icon: 'bell', title: 'Alertas Tempranas', desc: 'Detecta antes de que se vayan' },
      { icon: 'zap', title: 'Experiencia Variada', desc: 'Mantén el interés alto' },
    ],
    cta: 'Reduce tu abandono →',
    ctaNote: 'Sistema de retención automatizado',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'trending-down', text: '35% abandono promedio' },
    description:
      '🎯 El 35% de tus socios se irá este año. ¿Sabes por qué?\n\nEntender las razones del abandono es el primer paso para retener a tus clientes.\n\n✨ Lo que obtienes:\n• Conexión Emocional: Comunicación personalizada\n• Alertas Tempranas: Detecta antes de que se vayan\n• Experiencia Variada: Mantén el interés alto\n\n📊 35% abandono promedio anual\n\nReduce tu abandono →\n\nSistema de retención automatizado',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Retencion',
      'Abandono',
      'ChurnRate',
      'Fidelizacion',
      'ExperienciaCliente',
    ],
  },
  5: {
    id: 5,
    title: 'Nuevo socio listo en 2 minutos',
    day: 'Día 10',
    type: 'Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: '¿Cuánto tiempo pierdes registrando socios?',
    subtitle: 'Proceso manual: 20+ minutos. Con GymSpace: 2 minutos. Firma digital incluida.',
    totalSlides: 5,
    slides: [
      {
        title: 'Nuevo socio listo en 2 minutos, sin paperwork',
        subtitle: 'Onboarding digital + firma electrónica + QR activo al instante',
        layout: 'cover',
        warning: 'Onboarding lento = oportunidad perdida',
        stat: '10x',
        statLabel: 'más rápido que el proceso manual',
      },
      {
        title: 'El proceso tradicional',
        subtitle: 'Mucho papel, más fricción y más tiempo por cada alta',
        layout: 'process-breakdown',
        manualTotal: '20+ minutos por socio',
        steps: [
          { icon: 'file-signature', label: 'Imprimir contrato', time: '5 min' },
          { icon: 'clipboard-list', label: 'Llenar datos a mano', time: '10 min' },
          { icon: 'scan', label: 'Firmar y escanear', time: '5 min' },
          { icon: 'folder', label: 'Archivar físico', note: '¿Dónde quedó?' },
        ],
      },
      {
        title: 'Con GymSpace',
        subtitle: 'Todo desde el celular del socio, sin papel y sin demoras',
        layout: 'process-breakdown',
        digitalTotal: '2 minutos total',
        steps: [
          { icon: 'message-square', label: 'Recibe link por WhatsApp' },
          { icon: 'smartphone', label: 'Completa datos en su celular' },
          { icon: 'file-signature', label: 'Firma digitalmente' },
          { icon: 'qr-code', label: 'QR activo para entrenar' },
        ],
      },
      {
        title: 'Así se ve en la práctica',
        subtitle: 'Un flujo móvil pensado para convertir prospectos en socios activos',
        layout: 'mobile-onboarding-flow',
        mockupStages: [
          {
            icon: 'message-square',
            title: 'Invitación por WhatsApp',
            subtitle: 'Link seguro para completar registro',
          },
          {
            icon: 'smartphone',
            title: 'Formulario móvil',
            subtitle: 'Datos validados en tiempo real',
          },
          {
            icon: 'file-signature',
            title: 'Firma digital',
            subtitle: 'Aceptación legal sin imprimir nada',
          },
          {
            icon: 'qr-code',
            title: 'Acceso inmediato',
            subtitle: 'QR listo para ingresar al gimnasio',
          },
        ],
      },
      {
        title: 'Onboarding digital, sin paperwork',
        subtitle: 'Tu equipo ahorra tiempo y tu socio entra más rápido',
        layout: 'conversion-cta',
        proofPoints: [
          'Registro y firma desde su celular',
          'Contratos ordenados en un solo lugar',
          'Activación inmediata para entrenar',
        ],
        stat: '2 min',
        statLabel: 'de interés a socio activo',
      },
    ],
    stats: [
      { value: '20+', label: 'minutos proceso manual' },
      { value: '2', label: 'minutos con GymSpace' },
      { value: '10x', label: 'más rápido el onboarding' },
    ],
    features: [
      { icon: 'file-signature', title: 'Firma Digital', desc: 'Valida legalmente, sin papel' },
      { icon: 'smartphone', title: 'Desde el Celular', desc: 'El socio firma en su dispositivo' },
      { icon: 'clock', title: 'Activación Inmediata', desc: 'Listo para entrenar al instante' },
    ],
    cta: 'Empieza tu prueba gratis →',
    ctaNote: '30 días sin costo',
    hasFloatingBadge: false,
    description:
      '🎯 ¿Cuánto tiempo pierdes registrando socios?\n\nProceso manual: 20+ minutos. Con GymSpace: 2 minutos. Firma digital incluida.\n\n✨ Lo que obtienes:\n• Firma Digital: Valida legalmente, sin papel\n• Desde el Celular: El socio firma en su dispositivo\n• Activación Inmediata: Listo para entrenar al instante\n\n📊 10x más rápido el onboarding\n\nEmpieza tu prueba gratis →\n\n30 días sin costo',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Onboarding',
      'FirmaDigital',
      'Agilidad',
      'Registro',
    ],
  },
  6: {
    id: 6,
    title: 'Habla exactamente con quien necesitas',
    day: 'Día 12',
    type: 'Infografía',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: 'El error más común: enviar lo mismo a todos',
    subtitle: 'Con etiquetas puedes crear grupos y enviar mensajes específicos a cada uno.',
    stats: [
      { value: '30 días', label: 'sin asistir = grupo riesgo' },
      { value: '7 días', label: 'por vencer = grupo renovación' },
      { value: 'Nuevo', label: '= grupo onboarding' },
    ],
    features: [
      {
        icon: 'tags',
        title: 'Segmentación Inteligente',
        desc: 'Grupos automáticos por comportamiento',
      },
      {
        icon: 'message-square',
        title: 'Mensajes Relevantes',
        desc: 'Cada grupo recibe lo que necesita',
      },
      { icon: 'heart', title: 'Mayor Retención', desc: 'Comunicación personalizada = lealtad' },
    ],
    cta: "Comenta 'ETIQUETAS' →",
    ctaNote: 'Te mostramos cómo implementarlo',
    hasFloatingBadge: false,
    description:
      "🎯 El error más común: enviar lo mismo a todos\n\nCon etiquetas puedes crear grupos y enviar mensajes específicos a cada uno.\n\n✨ Lo que obtienes:\n• Segmentación Inteligente: Grupos automáticos por comportamiento\n• Mensajes Relevantes: Cada grupo recibe lo que necesita\n• Mayor Retención: Comunicación personalizada = lealtad\n\n📊 30 días sin asistir = grupo riesgo\n\nComenta 'ETIQUETAS' →\n\nTe mostramos cómo implementarlo",
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Segmentacion',
      'Etiquetas',
      'Personalizacion',
      'Marketing',
    ],
  },
  7: {
    id: 7,
    title: '7 errores que matan la rentabilidad de tu gimnasio',
    day: 'Día 14',
    type: 'Carousel',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: '¿Cuántos de estos errores estás cometiendo sin darte cuenta?',
    subtitle: 'Cada error que corriges es dinero que dejas de perder. Descúbrelos todos.',
    totalSlides: 9,
    slides: [
      {
        title: '7 errores que matan la rentabilidad',
        subtitle: 'Descúbrelos antes de que cierren tu gimnasio',
        content: 'cover',
        stat: '60%',
        statLabel: 'de gimnasios cierran por estos errores',
        layout: 'cover',
      },
      {
        title: 'Error #1',
        subtitle: 'El error más costoso',
        content: 'error-detail',
        error: 'No tener CRM de leads',
        description:
          'Cada persona que entra a tu gimnasio y no deja sus datos es dinero que nunca recuperarás.',
        solution: 'Registra cada visita. Un lead hoy es un socio mañana.',
        icon: 'users',
        stat: '70%',
        statLabel: 'de leads se pierden sin seguimiento',
        layout: 'error-detail',
      },
      {
        title: 'Error #2',
        subtitle: 'Confiar en la memoria',
        content: 'error-detail',
        error: 'Depender de recordatorios mentales',
        description:
          'Tu cerebro no está diseñado para recordar vencimientos, pagos pendientes y seguimientos.',
        solution: 'Automatiza recordatorios. El sistema nunca olvida.',
        icon: 'brain',
        stat: '12-18%',
        statLabel: 'de facturación perdida por olvidos',
        layout: 'error-detail',
      },
      {
        title: 'Error #3',
        subtitle: 'La señal de alarma ignorada',
        content: 'error-detail',
        error: 'No detectar inasistencias a tiempo',
        description:
          'Un socio que no asiste 7 días está a punto de irse. A los 30 días, ya es tarde.',
        solution: 'Alertas automáticas al día 7. Recupera antes de que se vayan.',
        icon: 'user-x',
        stat: '35%',
        statLabel: 'de abandono por falta de seguimiento',
        layout: 'error-detail',
      },
      {
        title: 'Error #4',
        subtitle: 'Comunicación reactiva',
        content: 'error-detail',
        error: 'Esperar a que el socio te contacte',
        description: 'Si solo respondes cuando te buscan, pierdes la oportunidad de generar valor.',
        solution: 'WhatsApp automatizado. 70% de apertura vs 20% del email.',
        icon: 'message-circle',
        stat: '70%',
        statLabel: 'tasa de apertura en WhatsApp',
        layout: 'error-detail',
      },
      {
        title: 'Error #5',
        subtitle: 'Volar a ciegas',
        content: 'error-detail',
        error: 'No medir métricas clave',
        description:
          'Sin conocer tu Churn Rate y LTV, estás tomando decisiones basadas en intuición, no en datos.',
        solution: 'Dashboard en tiempo real. Decisiones con datos.',
        icon: 'bar-chart-3',
        stat: '5%',
        statLabel: 'meta de churn rate mensual',
        layout: 'error-detail',
      },
      {
        title: 'Error #6',
        subtitle: 'El tiempo es dinero',
        content: 'error-detail',
        error: 'Procesos manuales lentos',
        description:
          '20 minutos para registrar un socio manualmente es tiempo que podrías invertir en vender más.',
        solution: 'Onboarding en 2 minutos. Firma digital incluida.',
        icon: 'clock',
        stat: '10x',
        statLabel: 'más rápido con digitalización',
        layout: 'error-detail',
      },
      {
        title: 'Error #7',
        subtitle: 'El caos de las apps',
        content: 'error-detail',
        error: 'Usar múltiples herramientas',
        description:
          'Excel + WhatsApp + Calendario + Finanzas = datos inconsistentes y errores humanos.',
        solution: 'Una plataforma. Todos tus datos en un solo lugar.',
        icon: 'layers',
        stat: '5→1',
        statLabel: 'apps consolidadas',
        layout: 'error-detail',
      },
      {
        title: '¿Listo para dejar de perder dinero?',
        subtitle: 'Cada error que corriges es una oportunidad de crecimiento',
        content: 'final-cta',
        stat: '25%',
        statLabel: 'reducción promedio en abandono',
        features: [
          { icon: 'target', title: 'Identifica', desc: 'Reconoce qué errores cometes' },
          { icon: 'zap', title: 'Corrige', desc: 'Implementa soluciones rápidas' },
          { icon: 'trending-up', title: 'Crece', desc: 'Resultados medibles en 30 días' },
        ],
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '7', label: 'errores comunes identificados' },
      { value: '25%', label: 'reducción promedio en abandono' },
      { value: '40%', label: 'ahorro en tiempo administrativo' },
    ],
    features: [
      { icon: 'target', title: 'Identifica', desc: 'Reconoce qué errores cometes' },
      { icon: 'zap', title: 'Corrige', desc: 'Implementa soluciones rápidas' },
      { icon: 'trending-up', title: 'Crece', desc: 'Resultados medibles en 30 días' },
    ],
    cta: 'Empieza tu prueba gratis →',
    ctaNote: '30 días sin costo · Sin tarjeta',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'alert-circle', text: '7 errores críticos' },
    description:
      '🎯 ¿Cuántos de estos errores estás cometiendo sin darte cuenta?\n\nCada error que corriges es dinero que dejas de perder. Descúbrelos todos.\n\n✨ Lo que obtienes:\n• Identifica: Reconoce qué errores cometes\n• Corrige: Implementa soluciones rápidas\n• Crece: Resultados medibles en 30 días\n\n📊 7 errores comunes identificados\n\nEmpieza tu prueba gratis →\n\n30 días sin costo · Sin tarjeta',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Errores',
      'Rentabilidad',
      'Eficiencia',
      'MejoraContinua',
    ],
  },
  8: {
    id: 8,
    title: 'El caos de usar 5 apps diferentes',
    day: 'Día 19',
    type: 'Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: '¿Cuántas apps abres antes de las 9 AM?',
    subtitle: 'Cada app que agregas es una oportunidad de error. Es hora de simplificar.',
    totalSlides: 6,
    slides: [
      {
        title: 'El caos de las múltiples apps',
        subtitle: 'Mientras más apps, más problemas',
        content: 'cover',
        stat: '5+',
        statLabel: 'apps usadas en promedio',
        layout: 'cover',
      },
      {
        title: 'El stack tradicional',
        subtitle: 'Una app para cada cosa',
        content: 'app-list',
        apps: [
          { icon: 'grid', name: 'Excel', problem: 'Datos desactualizados, errores manuales' },
          { icon: 'wallet', name: 'Finanzas', problem: 'No integrada con membresías' },
          {
            icon: 'message-circle',
            name: 'WhatsApp',
            problem: 'Mensajes uno por uno, sin historial',
          },
          { icon: 'calendar', name: 'Calendario', problem: 'Sin conexión a asistencias' },
          { icon: 'bar-chart-3', name: 'Reportes', problem: 'Datos inconsistentes entre apps' },
        ],
        layout: 'app-list',
      },
      {
        title: 'El costo de la fragmentación',
        subtitle: 'Lo que no ves te está costando dinero',
        content: 'cost-breakdown',
        costs: [
          {
            icon: 'clock',
            label: 'Tiempo perdido',
            value: '2-3 horas diarias',
            desc: 'Cambiando entre apps y copiando datos',
          },
          {
            icon: 'alert-circle',
            label: 'Errores humanos',
            value: '12-18%',
            desc: 'De facturación perdida por errores de transcripción',
          },
          {
            icon: 'users',
            label: 'Socios frustrados',
            value: '35%',
            desc: 'Abandono por mala experiencia administrativa',
          },
        ],
        layout: 'cost-breakdown',
      },
      {
        title: 'La solución',
        subtitle: 'Una plataforma, todos tus datos',
        content: 'solution-showcase',
        features: [
          { icon: 'users', title: 'Miembros', desc: 'Base de datos centralizada' },
          { icon: 'credit-card', title: 'Pagos', desc: 'Integrado con membresías' },
          { icon: 'message-circle', title: 'WhatsApp', desc: 'Automatizado y con historial' },
          { icon: 'calendar', title: 'Clases', desc: 'Conectado a asistencias' },
          { icon: 'bar-chart-3', title: 'Reportes', desc: 'Datos en tiempo real' },
        ],
        stat: '1',
        statLabel: 'plataforma unificada',
        layout: 'solution-showcase',
      },
      {
        title: 'Beneficios de unificar',
        subtitle: 'Menos apps, más resultados',
        content: 'benefits',
        benefits: [
          {
            icon: 'clock',
            title: 'Ahorra 2 horas diarias',
            desc: 'Todo en un solo lugar, sin cambiar de app',
          },
          {
            icon: 'check-circle',
            title: 'Cero errores de transcripción',
            desc: 'Datos consistentes en todo el sistema',
          },
          {
            icon: 'trending-up',
            title: 'Toma decisiones rápido',
            desc: 'Dashboard unificado con métricas reales',
          },
          {
            icon: 'heart',
            title: 'Mejor experiencia',
            desc: 'Socios felices con procesos fluidos',
          },
        ],
        layout: 'benefits',
      },
      {
        title: '¿Listo para simplificar?',
        subtitle: 'Deja el caos de las apps atrás',
        content: 'final-cta',
        stat: '5→1',
        statLabel: 'apps consolidadas',
        features: [
          { icon: 'layers', title: 'Unifica', desc: 'Todas tus herramientas en una' },
          { icon: 'zap', title: 'Ahorra tiempo', desc: '2 horas más al día' },
          { icon: 'trending-up', title: 'Crece', desc: 'Decisiones con datos claros' },
        ],
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '5→1', label: 'apps consolidadas' },
      { value: '2h', label: 'ahorro diario de tiempo' },
      { value: '0', label: 'errores de transcripción' },
    ],
    features: [
      { icon: 'layers', title: 'Todo Integrado', desc: 'Miembros, pagos, clases, comunicación' },
      { icon: 'check-circle', title: 'Datos Consistentes', desc: 'Una sola fuente de verdad' },
      { icon: 'zap', title: 'Sin Complejidad', desc: 'Interfaz unificada, fácil de usar' },
    ],
    cta: 'Unifica tu operación →',
    ctaNote: 'Prueba gratis 30 días',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'layers', text: '5 apps → 1 plataforma' },
    description:
      '🎯 ¿Cuántas apps abres antes de las 9 AM?\n\nCada app que agregas es una oportunidad de error. Es hora de simplificar.\n\n✨ Lo que obtienes:\n• Todo Integrado: Miembros, pagos, clases, comunicación\n• Datos Consistentes: Una sola fuente de verdad\n• Sin Complejidad: Interfaz unificada, fácil de usar\n\n📊 5→1 apps consolidadas\n\nUnifica tu operación →\n\nPrueba gratis 30 días',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Unificacion',
      'Integracion',
      'Productividad',
      'Eficiencia',
    ],
  },
  9: {
    id: 9,
    title: 'Check-in en 1 segundo con QR',
    day: 'Día 21',
    type: 'Reel + Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: 'Sin llaves. Sin tarjetas. Sin problemas.',
    subtitle: 'El socio muestra su QR en el celular, staff escanea, listo. Registro automático.',
    stats: [
      { value: '1s', label: 'tiempo de check-in' },
      { value: '0', label: 'tarjetas físicas necesarias' },
      { value: '100%', label: 'registro automático' },
    ],
    features: [
      { icon: 'qr-code', title: 'Código QR Personal', desc: 'Cada socio tiene el suyo en la app' },
      { icon: 'scan', title: 'Escaneo Rápido', desc: 'Cualquier celular puede escanear' },
      {
        icon: 'clipboard-list',
        title: 'Asistencia Automática',
        desc: 'Registro sin intervención manual',
      },
    ],
    cta: 'Prueba gratis 30 días →',
    ctaNote: 'Implementación inmediata',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'zap', text: '1 segundo de check-in' },
    description:
      '🎯 Sin llaves. Sin tarjetas. Sin problemas.\n\nEl socio muestra su QR en el celular, staff escanea, listo. Registro automático.\n\n✨ Lo que obtienes:\n• Código QR Personal: Cada socio tiene el suyo en la app\n• Escaneo Rápido: Cualquier celular puede escanear\n• Asistencia Automática: Registro sin intervención manual\n\n📊 1s tiempo de check-in\n\nPrueba gratis 30 días →\n\nImplementación inmediata',
    hashtags: ['GymSpace', 'Gimnasio', 'Fitness', 'QR', 'CheckIn', 'Tecnologia', 'Automatizacion'],
  },
  10: {
    id: 10,
    title: 'Cómo reducir el abandono un 25%',
    day: 'Día 23',
    type: 'Carousel',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: 'El 35% de abandono es promedio, pero no tiene que ser el tuyo',
    subtitle:
      'Con un sistema que te alerta de inasistencias, puedes bajar ese número significativamente.',
    totalSlides: 3,
    slides: [
      {
        title: 'El problema',
        content: 'stat-focus',
        stat: { value: '35%', label: 'abandono promedio' },
        subtitle: 'Sin sistema de detección temprana',
        layout: 'center-focus',
      },
      {
        title: 'La solución',
        subtitle: 'Un proceso claro para recuperar socios en riesgo',
        content: 'slide-list',
        items: [
          { number: '1', title: 'Detecta', desc: 'Alerta a los 7 días sin asistir' },
          { number: '2', title: 'Contacta', desc: 'Mensaje personalizado de recuperación' },
          { number: '3', title: 'Retén', desc: 'Ofrece valor, no descuentos' },
        ],
        layout: 'numbered-list',
      },
      {
        title: 'El resultado',
        content: 'stat-focus',
        stat: { value: '25%', label: 'menos abandono' },
        subtitle: 'Promedio de clientes GymSpace',
        layout: 'center-focus',
      },
    ],
    stats: [
      { value: '35%', label: 'abandono promedio industria' },
      { value: '25%', label: 'reducción posible' },
      { value: '15 días', label: 'para detectar inasistencias' },
    ],
    features: [
      { icon: 'bell', title: 'Alertas Tempranas', desc: 'Sistema avisa cuando alguien falta' },
      {
        icon: 'message-circle',
        title: 'Contacto Proactivo',
        desc: 'Recupera antes de que se vayan',
      },
      { icon: 'help-circle', title: 'Encuesta de Salida', desc: 'Aprende por qué se van' },
    ],
    cta: '¿Mides tu churn rate? →',
    ctaNote: 'Comenta y te ayudamos',
    hasFloatingBadge: false,
    description:
      '🎯 El 35% de abandono es promedio, pero no tiene que ser el tuyo\n\nCon un sistema que te alerta de inasistencias, puedes bajar ese número significativamente.\n\n✨ Lo que obtienes:\n• Alertas Tempranas: Sistema avisa cuando alguien falta\n• Contacto Proactivo: Recupera antes de que se vayan\n• Encuesta de Salida: Aprende por qué se van\n\n📊 35% abandono promedio industria\n\n¿Mides tu churn rate? →\n\nComenta y te ayudamos',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'ChurnRate',
      'Retencion',
      'Fidelizacion',
      'Alertas',
    ],
  },
  11: {
    id: 11,
    title: 'Dashboard en tiempo real',
    day: 'Día 25',
    type: 'Single Image',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: 'Tu negocio en tiempo real, en tu bolsillo',
    subtitle:
      'Abrís la app y ves: socios hoy, ingresos vs mes anterior, pagos pendientes, leads nuevos...',
    stats: [
      { value: '24/7', label: 'visibilidad de tu negocio' },
      { value: '0', label: 'reportes manuales necesarios' },
      { value: '∞', label: 'insights para decisiones' },
    ],
    features: [
      { icon: 'activity', title: 'Métricas en Vivo', desc: 'Datos actualizados al instante' },
      { icon: 'trending-up', title: 'Comparativas', desc: 'Mes vs mes, semana vs semana' },
      { icon: 'alert-circle', title: 'Alertas', desc: 'Notificaciones de lo importante' },
    ],
    cta: 'Agenda una demo →',
    ctaNote: 'Verás tu gimnasio en el dashboard',
    hasFloatingBadge: false,
    description:
      '🎯 Tu negocio en tiempo real, en tu bolsillo\n\nAbrís la app y ves: socios hoy, ingresos vs mes anterior, pagos pendientes, leads nuevos...\n\n✨ Lo que obtienes:\n• Métricas en Vivo: Datos actualizados al instante\n• Comparativas: Mes vs mes, semana vs semana\n• Alertas: Notificaciones de lo importante\n\n📊 24/7 visibilidad de tu negocio\n\nAgenda una demo →\n\nVerás tu gimnasio en el dashboard',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Dashboard',
      'Metricas',
      'TiempoReal',
      'Visualizacion',
    ],
  },
  12: {
    id: 12,
    title: 'De 100 a 500 socios en 6 meses',
    day: 'Día 16',
    type: 'Carousel',
    pilar: 'Social Proof',
    pilarColor: 'social',
    hook: 'Este podría ser tu gimnasio',
    subtitle: 'No se trata de trabajar más horas. Se trata de tener sistemas que escalan contigo.',
    totalSlides: 4,
    slides: [
      {
        title: 'De 100 a 500 socios',
        subtitle: 'Un gimnasio real que transformó su negocio',
        layout: 'growth-journey',
        badge: 'Caso de Éxito',
        stat: { from: '100', to: '500', period: '6 meses', growth: '+400%' },
        location: 'Gym Power - Lima, Perú',
        testimonial: {
          quote: 'Pasamos de luchar con Excel a tener 500 socios organizados',
          author: 'Carlos Mendoza, Dueño',
        },
      },
      {
        title: 'Cómo lo lograron',
        subtitle: 'Tres decisiones que aceleraron su crecimiento',
        content: 'slide-list',
        items: [
          { number: '1', title: 'Automatización', desc: '40% menos tiempo en admin' },
          { number: '2', title: 'Marketing', desc: 'Más tiempo para adquirir socios' },
          { number: '3', title: 'Expansión', desc: '3 nuevas sedes planificadas' },
        ],
        layout: 'numbered-list',
      },
      {
        title: 'El secreto',
        subtitle: 'Sistemas que escalan',
        content: 'feature-focus',
        stat: { value: '5x', label: 'crecimiento en 6 meses' },
        features: [
          { icon: 'rocket', title: 'Escalabilidad', desc: 'Sistema que crece contigo' },
          { icon: 'zap', title: 'Automatización', desc: 'Procesos sin intervención manual' },
          {
            icon: 'trending-up',
            title: 'Crecimiento',
            desc: 'De 100 a 500 sin contratar más staff',
          },
        ],
        layout: 'feature-focus',
      },
      {
        title: 'Tu turno',
        subtitle: 'Este podría ser tu gimnasio',
        content: 'final-cta',
        stat: '100→500',
        statLabel: 'socios en 6 meses',
        features: [
          { icon: 'rocket', title: 'Empieza Hoy', desc: '30 días de prueba gratis' },
          { icon: 'users', title: 'Implementación', desc: 'Te acompañamos paso a paso' },
          { icon: 'trending-up', title: 'Resultados', desc: 'Crecimiento medible en 30 días' },
        ],
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '100→500', label: 'socios en 6 meses' },
      { value: '40%', label: 'menos tiempo en admin' },
      { value: '3', label: 'nuevas sedes planificadas' },
    ],
    features: [
      { icon: 'rocket', title: 'Escalabilidad', desc: 'Sistema que crece contigo' },
      { icon: 'focus', title: 'Enfoque', desc: 'Tiempo para marketing y expansión' },
      { icon: 'users', title: 'Equipo', desc: 'Staff enfocado en valor, no tareas' },
    ],
    cta: '¿Listo para escalar? →',
    ctaNote: 'Empieza tu prueba gratis',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'rocket', text: '+400% crecimiento' },
    description:
      '🎯 Este podría ser tu gimnasio\n\nNo se trata de trabajar más horas. Se trata de tener sistemas que escalan contigo.\n\n✨ Lo que obtienes:\n• Escalabilidad: Sistema que crece contigo\n• Automatización: Procesos sin intervención manual\n• Enfoque: Tiempo para marketing y expansión\n\n📊 100→500 socios en 6 meses\n\n¿Listo para escalar? →\n\nEmpieza tu prueba gratis',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Crecimiento',
      'Escalabilidad',
      'CasoExito',
      'Transformacion',
    ],
  },
  13: {
    id: 13,
    title: 'El dolor de crecer: de 1 a 3+ sedes',
    day: 'Día 27',
    type: 'Carousel',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: 'Abrir 3 apps diferentes antes del desayuno no es crecer, es tortura',
    subtitle:
      'La gestión multi-sede no debería ser un dolor de cabeza. Descubre cómo escalar sin perder el control.',
    totalSlides: 7,
    slides: [
      {
        title: 'El dolor de crecer',
        subtitle: 'De 1 a 3+ sedes sin perder la cordura',
        content: 'cover',
        stat: '3x',
        statLabel: 'más complejo gestionar 3 sedes',
        layout: 'cover',
      },
      {
        title: 'El caos multi-sede',
        subtitle: 'Cada sede, un mundo aparte',
        content: 'app-list',
        apps: [
          { icon: 'building-2', name: 'Sede A', problem: 'Excel con datos diferentes' },
          { icon: 'building-2', name: 'Sede B', problem: 'WhatsApp del staff local' },
          { icon: 'building-2', name: 'Sede C', problem: 'App de finanzas separada' },
          { icon: 'repeat', name: 'Transferencias', problem: 'Manual, con errores' },
          { icon: 'bar-chart-3', name: 'Reportes', problem: 'Consolidar toma 1 día' },
        ],
        layout: 'app-list',
      },
      {
        title: 'El costo de la fragmentación',
        subtitle: 'Lo que no ves te está costando caro',
        content: 'cost-breakdown',
        costs: [
          {
            icon: 'clock',
            label: 'Tiempo perdido',
            value: '4-6h',
            desc: 'Consolidando reportes de 3 sedes diariamente',
          },
          {
            icon: 'alert-circle',
            label: 'Datos inconsistentes',
            value: '30%',
            desc: 'De información desactualizada entre sedes',
          },
          {
            icon: 'users',
            label: 'Clientes frustrados',
            value: '25%',
            desc: 'No pueden usar otra sede fácilmente',
          },
        ],
        layout: 'cost-breakdown',
      },
      {
        title: 'Centralización total',
        subtitle: 'Una plataforma, todas tus sedes',
        content: 'solution-showcase',
        features: [
          {
            icon: 'building-2',
            title: 'Todas las sedes',
            desc: 'Visibilidad unificada en un dashboard',
          },
          {
            icon: 'users',
            title: 'Socios centralizados',
            desc: 'Una base de datos para todas las ubicaciones',
          },
          {
            icon: 'credit-card',
            title: 'Pagos unificados',
            desc: 'Ingresos de todas las sedes en un lugar',
          },
          { icon: 'activity', title: 'Asistencia global', desc: 'Check-ins en cualquier sede' },
          {
            icon: 'bar-chart-3',
            title: 'Reportes consolidados',
            desc: 'Automáticos, en tiempo real',
          },
        ],
        stat: '1',
        statLabel: 'plataforma para todas las sedes',
        layout: 'solution-showcase',
      },
      {
        title: 'Comparativas inteligentes',
        subtitle: 'Sabe qué sede funciona mejor y por qué',
        content: 'comparison-insight',
        comparisons: [
          { metric: 'Ingresos', insight: 'Sede A supera a B un 23% - ¿Qué hacen diferente?' },
          { metric: 'Asistencia', insight: 'Horas pico diferentes por ubicación' },
          { metric: 'Abandono', insight: 'Sede C tiene mejor retención - Replicar su fórmula' },
        ],
        layout: 'comparison-insight',
      },
      {
        title: 'Transferencias sin fricción',
        subtitle: 'El socio es del gimnasio, no de la sede',
        content: 'benefits',
        benefits: [
          {
            icon: 'repeat',
            title: 'Usa cualquier sede',
            desc: 'El socio entrena donde le convenga',
          },
          {
            icon: 'shield',
            title: 'Control de acceso',
            desc: 'Permisos por sede, visibilidad global',
          },
          { icon: 'git-compare', title: 'Comparar sedes', desc: 'Identifica mejores prácticas' },
          { icon: 'zap', title: 'Escalar fácil', desc: 'Abre nueva sede en minutos, no en días' },
        ],
        layout: 'benefits',
      },
      {
        title: '¿Listo para escalar?',
        subtitle: 'Crece sin perder el control de tu negocio',
        content: 'final-cta',
        stat: '3→1',
        statLabel: 'sistemas consolidados',
        features: [
          { icon: 'building-2', title: 'Centraliza', desc: 'Todas las sedes en una plataforma' },
          { icon: 'bar-chart-3', title: 'Compara', desc: 'Identifica mejores prácticas' },
          { icon: 'rocket', title: 'Escala', desc: 'Abre nuevas sedes sin dolor' },
        ],
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '3+', label: 'sedes gestionadas' },
      { value: '1', label: 'plataforma unificada' },
      { value: '4-6h', label: 'ahorro diario en reportes' },
    ],
    features: [
      { icon: 'building-2', title: 'Multi-sede', desc: 'Todas tus ubicaciones en un lugar' },
      { icon: 'git-compare', title: 'Comparativas', desc: 'Qué sede está funcionando mejor' },
      { icon: 'repeat', title: 'Transferencias', desc: 'Clientes entre sedes sin fricción' },
    ],
    cta: 'Conoce los planes multi-sede →',
    ctaNote: 'Escalá sin perder el control',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'building-2', text: 'Multi-sede simplificado' },
    description:
      '🎯 Abrir 3 apps diferentes antes del desayuno no es crecer, es tortura\n\nLa gestión multi-sede no debería ser un dolor de cabeza. Descubre cómo escalar sin perder el control.\n\n✨ Lo que obtienes:\n• Multi-sede: Todas tus ubicaciones en un lugar\n• Comparativas: Qué sede está funcionando mejor\n• Transferencias: Clientes entre sedes sin fricción\n\n📊 3+ sedes gestionadas\n\nConoce los planes multi-sede →\n\nEscalá sin perder el control',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'Multisede',
      'Franquicia',
      'Escalabilidad',
      'Crecimiento',
    ],
  },
  14: {
    id: 14,
    title: 'Expectativa vs Realidad',
    day: 'Día 29',
    type: 'Meme',
    pilar: 'Behind Brand',
    pilarColor: 'brand',
    hook: '¿Te identificas? 😅',
    subtitle: 'Muchos abren gimnasios por pasión al fitness... y terminan en spreadsheets.',
    stats: [
      { value: '❤️', label: 'Pasión por fitness' },
      { value: '📊', label: 'Realidad con spreadsheets' },
      { value: '🚀', label: 'Solución: GymSpace' },
    ],
    features: [
      { icon: 'heart', title: 'Pasión', desc: 'Entrena, no administres' },
      { icon: 'monitor', title: 'Tecnología', desc: 'Debería liberarte, no encadenarte' },
      { icon: 'smile', title: 'Crecimiento', desc: 'Emocionante, no estresante' },
    ],
    cta: '¿Estás de acuerdo? 💪 →',
    ctaNote: 'Doble tap si te identificas',
    hasFloatingBadge: false,
    description:
      '🎯 ¿Te identificas? 😅\n\nMuchos abren gimnasios por pasión al fitness... y terminan en spreadsheets.\n\n✨ Lo que obtienes:\n• Pasión: Entrena, no administres\n• Tecnología: Debería liberarte, no encadenarte\n• Crecimiento: Emocionante, no estresante\n\n❤️ Pasión por fitness\n\n¿Estás de acuerdo? 💪 →\n\nDoble tap si te identificas',
    hashtags: ['GymSpace', 'Gimnasio', 'Fitness', 'Humor', 'Relatable', 'VidaDeGym', 'Emprendedor'],
  },
  15: {
    id: 15,
    title: 'Preguntas frecuentes',
    day: 'Día 30',
    type: 'FAQ',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: 'Tus dudas, resueltas',
    subtitle: '¿Cuánto tiempo toma implementar? ¿Necesito tarjeta? ¿Funciona en mi país?',
    stats: [
      { value: '<1', label: 'semana promedio de implementación' },
      { value: '0', label: 'tarjetas requeridas para prueba' },
      { value: 'LATAM', label: 'diseñado para la región' },
    ],
    features: [
      {
        icon: 'clock',
        title: 'Implementación Rápida',
        desc: 'La mayoría opera en menos de 1 semana',
      },
      { icon: 'credit-card', title: 'Sin Tarjeta', desc: '30 días gratis, sin compromiso' },
      { icon: 'globe', title: 'Multi-país', desc: 'Multi-moneda, español nativo' },
    ],
    cta: '¿Otra pregunta? →',
    ctaNote: 'Escríbenos por DM o WhatsApp',
    hasFloatingBadge: false,
    description:
      '🎯 Tus dudas, resueltas\n\n¿Cuánto tiempo toma implementar? ¿Necesito tarjeta? ¿Funciona en mi país?\n\n✨ Lo que obtienes:\n• Implementación Rápida: La mayoría opera en menos de 1 semana\n• Sin Tarjeta: 30 días gratis, sin compromiso\n• Multi-país: Multi-moneda, español nativo\n\n📊 <1 semana promedio de implementación\n\n¿Otra pregunta? →\n\nEscríbenos por DM o WhatsApp',
    hashtags: ['GymSpace', 'Gimnasio', 'Fitness', 'FAQ', 'Preguntas', 'Soporte', 'Implementacion'],
  },
  16: {
    id: 16,
    title: '30 días gratis. Sin tarjeta.',
    day: 'Día 32',
    type: 'CTA Fuerte',
    pilar: 'Problema/Solución',
    pilarColor: 'prob',
    hook: 'Nada que perder. Mucho que ganar.',
    subtitle: 'Has visto cómo otros reducen abandono 25%, automatizan WhatsApp con 70% apertura...',
    stats: [
      { value: '30', label: 'días de prueba gratis' },
      { value: '0', label: 'tarjetas de crédito' },
      { value: '∞', label: 'posibilidades de crecer' },
    ],
    features: [
      { icon: 'gift', title: 'Prueba Sin Riesgo', desc: '30 días completos, sin costo' },
      {
        icon: 'headphones',
        title: 'Soporte Incluido',
        desc: 'Te acompañamos en la implementación',
      },
      { icon: 'rocket', title: 'Empieza Hoy', desc: 'Link en bio para comenzar' },
    ],
    cta: 'Link en bio →',
    ctaNote: 'Empieza tu prueba ahora',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'gift', text: '30 días gratis' },
    description:
      '🎯 Nada que perder. Mucho que ganar.\n\nHas visto cómo otros reducen abandono 25%, automatizan WhatsApp con 70% apertura...\n\n✨ Lo que obtienes:\n• Prueba Sin Riesgo: 30 días completos, sin costo\n• Soporte Incluido: Te acompañamos en la implementación\n• Empieza Hoy: Link en bio para comenzar\n\n📊 30 días de prueba gratis\n\nLink en bio →\n\nEmpieza tu prueba ahora',
    hashtags: [
      'GymSpace',
      'Gimnasio',
      'Fitness',
      'PruebaGratis',
      'Oferta',
      'Soporte',
      'EmpiezaHoy',
    ],
  },
  17: {
    id: 17,
    title: 'Churn Rate: La métrica que define tu gimnasio',
    day: 'Día 33',
    type: 'Carousel',
    pilar: 'Educación',
    pilarColor: 'edu',
    hook: '¿Cuántos socios se te escapan cada mes sin que te des cuenta?',
    subtitle:
      'El Churn Rate es el indicador más importante de la salud de tu gimnasio. Aprende a medirlo y reducirlo.',
    totalSlides: 6,
    slides: [
      {
        title: 'Churn Rate',
        subtitle: '¿Cuántos socios abandonan tu gimnasio cada mes?',
        content: 'cover',
        stat: '35%',
        statLabel: 'abandono promedio anual en gimnasios',
        layout: 'cover',
      },
      {
        title: '¿Qué es el Churn Rate?',
        subtitle: 'La tasa de abandono que determina tu éxito',
        content: 'slide-list',
        items: [
          {
            number: '1',
            title: 'Definición',
            desc: '% de socios que dejan tu gimnasio en un período',
          },
          { number: '2', title: 'Ejemplo', desc: 'Si tienes 100 socios y 5 se van = 5% Churn' },
          { number: '3', title: 'Impacto', desc: 'Afecta directamente tus ingresos y crecimiento' },
        ],
        layout: 'numbered-list',
      },
      {
        title: 'El costo real del abandono',
        subtitle: 'Cada socio que se va es dinero que pierdes',
        content: 'comparison',
        before: {
          title: 'Churn Alto (10%)',
          items: ['Pierdes 10 socios/mes', 'Debes conseguir 10+ nuevos', 'Crecimiento estancado'],
        },
        after: {
          title: 'Churn Bajo (3%)',
          items: ['Pierdes solo 3 socios/mes', 'Crecimiento sostenible', 'Más rentabilidad'],
        },
        layout: 'two-col-comparison',
      },
      {
        title: 'Cómo calcular tu Churn Rate',
        subtitle: 'Fórmula simple pero poderosa',
        content: 'metric-detail',
        metricName: 'Fórmula del Churn Rate',
        metricValue: 'Cálculo mensual',
        description: 'Socios perdidos en el mes ÷ Total de socios al inicio del mes × 100',
        whyItMatters: 'Calcularlo mensualmente te permite detectar problemas antes de que crezcan.',
        icon: 'bar-chart-3',
        stat: 'Ejemplo',
        statLabel: '5 perdidos ÷ 100 total = 5% Churn',
        layout: 'metric-detail',
      },
      {
        title: 'Meta ideal de Churn Rate',
        subtitle: 'Benchmarks para gimnasios exitosos',
        content: 'slide-list',
        items: [
          { number: '1', title: 'Meta ideal', desc: 'Menos del 5% mensual (< 60% anual)' },
          { number: '2', title: 'Promedio LATAM', desc: '8-12% mensual (industria fitness)' },
          { number: '3', title: 'Excelente', desc: 'Menos del 3% mensual (< 36% anual)' },
        ],
        layout: 'numbered-list',
      },
      {
        title: 'Reduce tu Churn con GymSpace',
        subtitle: 'Herramientas para retener más socios',
        content: 'benefits',
        benefits: [
          {
            icon: 'bell',
            title: 'Alertas Tempranas',
            desc: 'Detecta socios en riesgo antes de que abandonen',
          },
          {
            icon: 'message-circle',
            title: 'Comunicación Proactiva',
            desc: 'WhatsApp automatizado para reenganchar',
          },
          {
            icon: 'heart',
            title: 'Seguimiento Personalizado',
            desc: 'Historial completo de cada socio',
          },
        ],
        stat: '25%',
        statLabel: 'reducción promedio en abandono',
        layout: 'final-cta',
      },
    ],
    stats: [
      { value: '35%', label: 'abandono promedio anual' },
      { value: '< 5%', label: 'meta mensual ideal' },
      { value: '25%', label: 'reducción con GymSpace' },
    ],
    features: [
      {
        icon: 'bar-chart-3',
        title: 'Dashboard de Churn',
        desc: 'Visualiza tu tasa de abandono en tiempo real',
      },
      {
        icon: 'bell',
        title: 'Alertas Inteligentes',
        desc: 'Te avisamos cuando un socio está en riesgo',
      },
      { icon: 'trending-down', title: 'Tendencias', desc: 'Análisis mensual de tu retención' },
    ],
    cta: 'Mide tu Churn Rate →',
    ctaNote: 'Prueba gratuita de 30 días',
    hasFloatingBadge: true,
    floatingBadge: { icon: 'bar-chart-3', text: '35% abandono promedio' },
    description:
      '🎯 ¿Cuántos socios se te escapan cada mes sin que te des cuenta?\n\nEl Churn Rate es el indicador más importante de la salud de tu gimnasio. Aprende a medirlo y reducirlo.\n\n✨ Lo que obtienes:\n• Dashboard de Churn: Visualiza tu tasa de abandono en tiempo real\n• Alertas Inteligentes: Te avisamos cuando un socio está en riesgo\n• Tendencias: Análisis mensual de tu retención\n\n📊 35% abandono promedio anual\n\nMide tu Churn Rate →\n\nPrueba gratuita de 30 días',
    hashtags: ['GymSpace', 'Gimnasio', 'Fitness', 'ChurnRate', 'Metricas', 'Retencion', 'Analisis'],
  },
};

// Icon SVGs mapping
const iconSVGs = {
  users: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>`,
  'message-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/><path d="M8 12h.01"/><path d="M12 12h.01"/><path d="M16 12h.01"/></svg>`,
  'bar-chart-3': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/></svg>`,
  'trending-down': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 18 13.5 8.5 8.5 13.5 1 6"/><polyline points="17 18 23 18 23 12"/></svg>`,
  'dollar-sign': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" x2="12" y1="2" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>`,
  coins: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="8" r="6"/><path d="M18.09 10.37A6 6 0 1 1 10.34 18"/><path d="M7 6h1v4"/><path d="m16.71 13.88.7.71-2.83 2.83"/></svg>`,
  wallet: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 7v10a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/></svg>`,
  target: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>`,
  'x-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/></svg>`,
  brain: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"/><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"/><path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"/><path d="M17.599 6.5a3 3 0 0 0 .399-1.375"/><path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"/><path d="M3.477 10.896a4 4 0 0 1 .585-.396"/><path d="M19.938 10.5a4 4 0 0 1 .585.396"/><path d="M6 18a4 4 0 0 1-1.967-.516"/><path d="M19.967 17.484A4 4 0 0 1 18 18"/></svg>`,
  'user-x': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="17" x2="22" y1="8" y2="13"/><line x1="22" x2="17" y1="8" y2="13"/></svg>`,
  'file-signature': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 19.5V9.5a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2Z"/><path d="M8 13h8"/><path d="M8 17h5"/><path d="M13 2v5"/><path d="m17 10 4-4-4-4"/></svg>`,
  smartphone: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/></svg>`,
  clock: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`,
  tags: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 5H2v7l6.29 6.29c.94.94 2.48.94 3.42 0l3.58-3.58c.94-.94.94-2.48 0-3.42L9 5Z"/><path d="M6 9.01V9"/><path d="m15 5 6.3 6.29a2.4 2.4 0 0 1 0 3.42l-3.58 3.58a2.4 2.4 0 0 1-3.42 0L9 16"/></svg>`,
  'message-square': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>`,
  heart: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>`,
  'trending-up': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>`,
  layers: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65"/><path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65"/></svg>`,
  puzzle: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z"/><path d="M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z"/><path d="M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z"/><path d="M15.536 8.088a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0L9.368 6.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0z"/><path d="M12 11h.01"/><path d="M12 17h.01"/></svg>`,
  zap: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>`,
  'qr-code': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="5" height="5" x="3" y="3" rx="1"/><rect width="5" height="5" x="16" y="3" rx="1"/><rect width="5" height="5" x="3" y="16" rx="1"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/><path d="M21 21v.01"/><path d="M12 7v3a2 2 0 0 1-2 2H7"/><path d="M3 12h.01"/><path d="M12 3h.01"/><path d="M12 16v.01"/><path d="M16 12h1"/><path d="M21 12v.01"/><path d="M12 21v-1"/></svg>`,
  scan: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/></svg>`,
  'clipboard-list': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="M12 11h4"/><path d="M12 16h4"/><path d="M8 11h.01"/><path d="M8 16h.01"/></svg>`,
  bell: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/></svg>`,
  'help-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><path d="M12 17h.01"/></svg>`,
  activity: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>`,
  'alert-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/></svg>`,
  rocket: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"/><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"/><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"/><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"/></svg>`,
  focus: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/></svg>`,
  'building-2': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 12h4"/><path d="M10 8h4"/><path d="M10 16h4"/><path d="M14 21v-2a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v2"/><path d="M6 21H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-2"/></svg>`,
  'git-compare': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M13 6h3a2 2 0 0 1 2 2v7"/><path d="M11 18H8a2 2 0 0 1-2-2V9"/></svg>`,
  repeat: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/></svg>`,
  monitor: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="3" rx="2"/><line x1="8" x2="16" y1="21" y2="21"/><line x1="12" x2="12" y1="17" y2="21"/></svg>`,
  smile: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" x2="9.01" y1="9" y2="9"/><line x1="15" x2="15.01" y1="9" y2="9"/></svg>`,
  'credit-card': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="5" rx="2"/><line x1="2" x2="22" y1="10" y2="10"/></svg>`,
  globe: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" x2="22" y1="12" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`,
  gift: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 12 20 22 4 22 4 12"/><rect width="20" height="5" x="2" y="7" rx="2"/><line x1="12" x2="12" y1="22" y2="7"/><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"/><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"/></svg>`,
  headphones: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 14v3a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-3"/><path d="M17 14v3a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-3"/><path d="M21 12c0-4.97-4.03-9-9-9s-9 4.03-9 9"/></svg>`,
  dumbbell: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6.5 6.5h11"/><path d="M6.5 17.5h11"/><path d="M6 20v-2a6 6 0 1 1 12 0v2"/><path d="M9 9a3 3 0 1 1 6 0v2H9V9z"/></svg>`,
  'arrow-right': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>`,
  download: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>`,
  grid: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/></svg>`,
  'chevron-left': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>`,
  'chevron-right': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>`,
  'zoom-in': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="11" x2="11" y1="8" y2="14"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`,
  'zoom-out': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="8" x2="14" y1="11" y2="11"/></svg>`,
  maximize: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M21 8V5a2 2 0 0 0-2-2h-3"/><path d="M3 16v3a2 2 0 0 0 2 2h3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/></svg>`,
  image: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/></svg>`,
  loader: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" x2="12" y1="2" y2="6"/><line x1="12" x2="12" y1="18" y2="22"/><line x1="4.93" x2="7.76" y1="4.93" y2="7.76"/><line x1="16.24" x2="19.07" y1="16.24" y2="19.07"/><line x1="2" x2="6" y1="12" y2="12"/><line x1="18" x2="22" y1="12" y2="12"/><line x1="4.93" x2="7.76" y1="19.07" y2="16.24"/><line x1="16.24" x2="19.07" y1="7.76" y2="4.93"/></svg>`,
  package: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7.5 4.27 9 5.15"/><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/></svg>`,
  check: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`,
  share: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" x2="12" y1="2" y2="15"/></svg>`,
  folder: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg>`,
  eye: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg>`,
  'eye-off': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/><path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"/><path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"/><line x1="2" x2="22" y1="2" y2="22"/></svg>`,
  layout: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M9 21V9"/></svg>`,
  'check-circle': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="16 10 12 14 8 10"/></svg>`,
  'arrow-left': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5"/><path d="m12 19-7-7 7-7"/></svg>`,
  'arrow-up': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 7-7 7 7"/><path d="M12 19V5"/></svg>`,
  minus: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/></svg>`,
};

// Export for use in other modules
export { postsData, iconSVGs };

// Expose globals for browser ES6 module imports
declare global {
  interface Window {
    postsData: PostsData;
    iconSVGs: Record<string, string>;
  }
}

if (typeof window !== 'undefined') {
  window.postsData = postsData;
  window.iconSVGs = iconSVGs;
}
